-- Peugeot, Renault, Skoda, TOGG, Toyota, Tofaş, Volkswagen modelleri (lib/categories.ts).
insert into categories (slug, name)
values
  ('tasitlar_otomobil-peugeot-106', 'Otomobil › Peugeot › 106'),
  ('tasitlar_otomobil-peugeot-107', 'Otomobil › Peugeot › 107'),
  ('tasitlar_otomobil-peugeot-205', 'Otomobil › Peugeot › 205'),
  ('tasitlar_otomobil-peugeot-206', 'Otomobil › Peugeot › 206'),
  ('tasitlar_otomobil-peugeot-206-plus', 'Otomobil › Peugeot › 206 +'),
  ('tasitlar_otomobil-peugeot-207', 'Otomobil › Peugeot › 207'),
  ('tasitlar_otomobil-peugeot-208', 'Otomobil › Peugeot › 208'),
  ('tasitlar_otomobil-peugeot-e-208', 'Otomobil › Peugeot › e-208'),
  ('tasitlar_otomobil-peugeot-301', 'Otomobil › Peugeot › 301'),
  ('tasitlar_otomobil-peugeot-305', 'Otomobil › Peugeot › 305'),
  ('tasitlar_otomobil-peugeot-306', 'Otomobil › Peugeot › 306'),
  ('tasitlar_otomobil-peugeot-307', 'Otomobil › Peugeot › 307'),
  ('tasitlar_otomobil-peugeot-308', 'Otomobil › Peugeot › 308'),
  ('tasitlar_otomobil-peugeot-e-308', 'Otomobil › Peugeot › e-308'),
  ('tasitlar_otomobil-peugeot-405', 'Otomobil › Peugeot › 405'),
  ('tasitlar_otomobil-peugeot-406', 'Otomobil › Peugeot › 406'),
  ('tasitlar_otomobil-peugeot-407', 'Otomobil › Peugeot › 407'),
  ('tasitlar_otomobil-peugeot-508', 'Otomobil › Peugeot › 508'),
  ('tasitlar_otomobil-peugeot-605', 'Otomobil › Peugeot › 605'),
  ('tasitlar_otomobil-peugeot-607', 'Otomobil › Peugeot › 607'),
  ('tasitlar_otomobil-peugeot-807', 'Otomobil › Peugeot › 807'),
  ('tasitlar_otomobil-peugeot-pars', 'Otomobil › Peugeot › Pars'),
  ('tasitlar_otomobil-peugeot-rcz', 'Otomobil › Peugeot › RCZ'),
  ('tasitlar_otomobil-peugeot-1007', 'Otomobil › Peugeot › 1007'),
  ('tasitlar_otomobil-renault-clio', 'Otomobil › Renault › Clio'),
  ('tasitlar_otomobil-renault-espace', 'Otomobil › Renault › Espace'),
  ('tasitlar_otomobil-renault-fluence', 'Otomobil › Renault › Fluence'),
  ('tasitlar_otomobil-renault-fluence-ze', 'Otomobil › Renault › Fluence Z.E.'),
  ('tasitlar_otomobil-renault-grand-scenic', 'Otomobil › Renault › Grand Scenic'),
  ('tasitlar_otomobil-renault-grand-modus', 'Otomobil › Renault › Grand Modüs'),
  ('tasitlar_otomobil-renault-laguna', 'Otomobil › Renault › Laguna'),
  ('tasitlar_otomobil-renault-latitude', 'Otomobil › Renault › Latitude'),
  ('tasitlar_otomobil-renault-megane', 'Otomobil › Renault › Megane'),
  ('tasitlar_otomobil-renault-megane-e-tech', 'Otomobil › Renault › Megane E-Tech'),
  ('tasitlar_otomobil-renault-modus', 'Otomobil › Renault › Modus'),
  ('tasitlar_otomobil-renault-safrane', 'Otomobil › Renault › Safrane'),
  ('tasitlar_otomobil-renault-scenic', 'Otomobil › Renault › Scenic'),
  ('tasitlar_otomobil-renault-symbol', 'Otomobil › Renault › Symbol'),
  ('tasitlar_otomobil-renault-taliant', 'Otomobil › Renault › Taliant'),
  ('tasitlar_otomobil-renault-talisman', 'Otomobil › Renault › Talisman'),
  ('tasitlar_otomobil-renault-twingo', 'Otomobil › Renault › Twingo'),
  ('tasitlar_otomobil-renault-twizy', 'Otomobil › Renault › Twizy'),
  ('tasitlar_otomobil-renault-vel-satis', 'Otomobil › Renault › Vel Satis'),
  ('tasitlar_otomobil-renault-zoe', 'Otomobil › Renault › ZOE'),
  ('tasitlar_otomobil-renault-r5-e-tech', 'Otomobil › Renault › R5 E-Tech'),
  ('tasitlar_otomobil-renault-r-5', 'Otomobil › Renault › R 5'),
  ('tasitlar_otomobil-renault-r-9', 'Otomobil › Renault › R 9'),
  ('tasitlar_otomobil-renault-r-11', 'Otomobil › Renault › R 11'),
  ('tasitlar_otomobil-renault-r-12', 'Otomobil › Renault › R 12'),
  ('tasitlar_otomobil-renault-r-19', 'Otomobil › Renault › R 19'),
  ('tasitlar_otomobil-renault-r-21', 'Otomobil › Renault › R 21'),
  ('tasitlar_otomobil-renault-r-25', 'Otomobil › Renault › R 25'),
  ('tasitlar_otomobil-skoda-citigo', 'Otomobil › Skoda › Citigo'),
  ('tasitlar_otomobil-skoda-fabia', 'Otomobil › Skoda › Fabia'),
  ('tasitlar_otomobil-skoda-favorit', 'Otomobil › Skoda › Favorit'),
  ('tasitlar_otomobil-skoda-felicia', 'Otomobil › Skoda › Felicia'),
  ('tasitlar_otomobil-skoda-forman', 'Otomobil › Skoda › Forman'),
  ('tasitlar_otomobil-skoda-octavia', 'Otomobil › Skoda › Octavia'),
  ('tasitlar_otomobil-skoda-rapid', 'Otomobil › Skoda › Rapid'),
  ('tasitlar_otomobil-skoda-roomster', 'Otomobil › Skoda › Roomster'),
  ('tasitlar_otomobil-skoda-scala', 'Otomobil › Skoda › Scala'),
  ('tasitlar_otomobil-skoda-superb', 'Otomobil › Skoda › Superb'),
  ('tasitlar_otomobil-togg-t10f', 'Otomobil › TOGG › T10F'),
  ('tasitlar_otomobil-togg-v1', 'Otomobil › TOGG › V1'),
  ('tasitlar_otomobil-togg-v2', 'Otomobil › TOGG › V2'),
  ('tasitlar_otomobil-toyota-auris', 'Otomobil › Toyota › Auris'),
  ('tasitlar_otomobil-toyota-avensis', 'Otomobil › Toyota › Avensis'),
  ('tasitlar_otomobil-toyota-avalon', 'Otomobil › Toyota › Avalon'),
  ('tasitlar_otomobil-toyota-camry', 'Otomobil › Toyota › Camry'),
  ('tasitlar_otomobil-toyota-carina', 'Otomobil › Toyota › Carina'),
  ('tasitlar_otomobil-toyota-celica', 'Otomobil › Toyota › Celica'),
  ('tasitlar_otomobil-toyota-corolla', 'Otomobil › Toyota › Corolla'),
  ('tasitlar_otomobil-toyota-corona', 'Otomobil › Toyota › Corona'),
  ('tasitlar_otomobil-toyota-cressida', 'Otomobil › Toyota › Cressida'),
  ('tasitlar_otomobil-toyota-gt86', 'Otomobil › Toyota › GT86'),
  ('tasitlar_otomobil-toyota-mr2', 'Otomobil › Toyota › MR2'),
  ('tasitlar_otomobil-toyota-prius', 'Otomobil › Toyota › Prius'),
  ('tasitlar_otomobil-toyota-starlet', 'Otomobil › Toyota › Starlet'),
  ('tasitlar_otomobil-toyota-supra', 'Otomobil › Toyota › Supra'),
  ('tasitlar_otomobil-toyota-tercel', 'Otomobil › Toyota › Tercel'),
  ('tasitlar_otomobil-toyota-urban-cruiser', 'Otomobil › Toyota › Urban Cruiser'),
  ('tasitlar_otomobil-toyota-verso', 'Otomobil › Toyota › Verso'),
  ('tasitlar_otomobil-toyota-yaris', 'Otomobil › Toyota › Yaris'),
  ('tasitlar_otomobil-tofas-dogan', 'Otomobil › Tofaş › Doğan'),
  ('tasitlar_otomobil-tofas-kartal', 'Otomobil › Tofaş › Kartal'),
  ('tasitlar_otomobil-tofas-murat', 'Otomobil › Tofaş › Murat'),
  ('tasitlar_otomobil-tofas-sahin', 'Otomobil › Tofaş › Şahin'),
  ('tasitlar_otomobil-tofas-serce', 'Otomobil › Tofaş › Serçe'),
  ('tasitlar_otomobil-volkswagen-arteon', 'Otomobil › Volkswagen › Arteon'),
  ('tasitlar_otomobil-volkswagen-beetle', 'Otomobil › Volkswagen › Beetle'),
  ('tasitlar_otomobil-volkswagen-bora', 'Otomobil › Volkswagen › Bora'),
  ('tasitlar_otomobil-volkswagen-eos', 'Otomobil › Volkswagen › EOS'),
  ('tasitlar_otomobil-volkswagen-fox', 'Otomobil › Volkswagen › FOX'),
  ('tasitlar_otomobil-volkswagen-golf', 'Otomobil › Volkswagen › Golf'),
  ('tasitlar_otomobil-volkswagen-id-3', 'Otomobil › Volkswagen › ID.3'),
  ('tasitlar_otomobil-volkswagen-id-7', 'Otomobil › Volkswagen › ID.7'),
  ('tasitlar_otomobil-volkswagen-jetta', 'Otomobil › Volkswagen › Jetta'),
  ('tasitlar_otomobil-volkswagen-lupo', 'Otomobil › Volkswagen › Lupo'),
  ('tasitlar_otomobil-volkswagen-passat', 'Otomobil › Volkswagen › Passat'),
  ('tasitlar_otomobil-volkswagen-passat-alltrack', 'Otomobil › Volkswagen › Passat Alltrack'),
  ('tasitlar_otomobil-volkswagen-passat-variant', 'Otomobil › Volkswagen › Passat Variant'),
  ('tasitlar_otomobil-volkswagen-phaeton', 'Otomobil › Volkswagen › Phaeton'),
  ('tasitlar_otomobil-volkswagen-polo', 'Otomobil › Volkswagen › Polo'),
  ('tasitlar_otomobil-volkswagen-scirocco', 'Otomobil › Volkswagen › Scirocco'),
  ('tasitlar_otomobil-volkswagen-sharan', 'Otomobil › Volkswagen › Sharan'),
  ('tasitlar_otomobil-volkswagen-touran', 'Otomobil › Volkswagen › Touran'),
  ('tasitlar_otomobil-volkswagen-up-club', 'Otomobil › Volkswagen › Up Club'),
  ('tasitlar_otomobil-volkswagen-vw-cc', 'Otomobil › Volkswagen › VW CC'),
  ('tasitlar_otomobil-volkswagen-vento', 'Otomobil › Volkswagen › Vento')
on conflict (slug) do nothing;
