-- BMW 7 Serisi altı modeller (lib/categories.ts OTOMOBIL_MARKA_MODELS.bmw ile uyumlu).
insert into categories (slug, name)
values
  ('tasitlar_otomobil-bmw-7-serisi-725d', 'Otomobil › BMW › 7 Serisi › 725d'),
  ('tasitlar_otomobil-bmw-7-serisi-725d-long', 'Otomobil › BMW › 7 Serisi › 725d Long'),
  ('tasitlar_otomobil-bmw-7-serisi-725tds', 'Otomobil › BMW › 7 Serisi › 725tds'),
  ('tasitlar_otomobil-bmw-7-serisi-728i', 'Otomobil › BMW › 7 Serisi › 728i'),
  ('tasitlar_otomobil-bmw-7-serisi-728i-long', 'Otomobil › BMW › 7 Serisi › 728i Long'),
  ('tasitlar_otomobil-bmw-7-serisi-730d', 'Otomobil › BMW › 7 Serisi › 730d'),
  ('tasitlar_otomobil-bmw-7-serisi-730d-long', 'Otomobil › BMW › 7 Serisi › 730d Long'),
  ('tasitlar_otomobil-bmw-7-serisi-730d-xdrive', 'Otomobil › BMW › 7 Serisi › 730d xDrive'),
  ('tasitlar_otomobil-bmw-7-serisi-730d-xdrive-long', 'Otomobil › BMW › 7 Serisi › 730d xDrive Long'),
  ('tasitlar_otomobil-bmw-7-serisi-730i', 'Otomobil › BMW › 7 Serisi › 730i'),
  ('tasitlar_otomobil-bmw-7-serisi-730i-long', 'Otomobil › BMW › 7 Serisi › 730i Long'),
  ('tasitlar_otomobil-bmw-7-serisi-735i', 'Otomobil › BMW › 7 Serisi › 735i'),
  ('tasitlar_otomobil-bmw-7-serisi-735i-long', 'Otomobil › BMW › 7 Serisi › 735i Long'),
  ('tasitlar_otomobil-bmw-7-serisi-740d', 'Otomobil › BMW › 7 Serisi › 740d'),
  ('tasitlar_otomobil-bmw-7-serisi-740d-xdrive', 'Otomobil › BMW › 7 Serisi › 740d xDrive'),
  ('tasitlar_otomobil-bmw-7-serisi-740d-xdrive-long', 'Otomobil › BMW › 7 Serisi › 740d xDrive Long'),
  ('tasitlar_otomobil-bmw-7-serisi-740e-xdrive-long', 'Otomobil › BMW › 7 Serisi › 740e xDrive Long'),
  ('tasitlar_otomobil-bmw-7-serisi-740i', 'Otomobil › BMW › 7 Serisi › 740i'),
  ('tasitlar_otomobil-bmw-7-serisi-740i-long', 'Otomobil › BMW › 7 Serisi › 740i Long'),
  ('tasitlar_otomobil-bmw-7-serisi-745d', 'Otomobil › BMW › 7 Serisi › 745d'),
  ('tasitlar_otomobil-bmw-7-serisi-745i', 'Otomobil › BMW › 7 Serisi › 745i'),
  ('tasitlar_otomobil-bmw-7-serisi-745i-long', 'Otomobil › BMW › 7 Serisi › 745i Long'),
  ('tasitlar_otomobil-bmw-7-serisi-750d-xdrive-long', 'Otomobil › BMW › 7 Serisi › 750d xDrive Long'),
  ('tasitlar_otomobil-bmw-7-serisi-750i', 'Otomobil › BMW › 7 Serisi › 750i'),
  ('tasitlar_otomobil-bmw-7-serisi-750-ial', 'Otomobil › BMW › 7 Serisi › 750 ial'),
  ('tasitlar_otomobil-bmw-7-serisi-750i-long', 'Otomobil › BMW › 7 Serisi › 750i Long'),
  ('tasitlar_otomobil-bmw-7-serisi-750i-xdrive', 'Otomobil › BMW › 7 Serisi › 750i xDrive'),
  ('tasitlar_otomobil-bmw-7-serisi-750i-xdrive-long', 'Otomobil › BMW › 7 Serisi › 750i xDrive Long'),
  ('tasitlar_otomobil-bmw-7-serisi-760i', 'Otomobil › BMW › 7 Serisi › 760i'),
  ('tasitlar_otomobil-bmw-7-serisi-760i-long', 'Otomobil › BMW › 7 Serisi › 760i Long')
on conflict (slug) do nothing;
