-- BMW 3 Serisi altı modeller (lib/categories.ts OTOMOBIL_MARKA_MODELS.bmw ile uyumlu).
insert into categories (slug, name)
values
  ('tasitlar_otomobil-bmw-3-serisi-315', 'Otomobil › BMW › 3 Serisi › 315'),
  ('tasitlar_otomobil-bmw-3-serisi-316', 'Otomobil › BMW › 3 Serisi › 316'),
  ('tasitlar_otomobil-bmw-3-serisi-316ci', 'Otomobil › BMW › 3 Serisi › 316Ci'),
  ('tasitlar_otomobil-bmw-3-serisi-316i', 'Otomobil › BMW › 3 Serisi › 316i'),
  ('tasitlar_otomobil-bmw-3-serisi-316ti', 'Otomobil › BMW › 3 Serisi › 316ti'),
  ('tasitlar_otomobil-bmw-3-serisi-318ci', 'Otomobil › BMW › 3 Serisi › 318Ci'),
  ('tasitlar_otomobil-bmw-3-serisi-318d', 'Otomobil › BMW › 3 Serisi › 318d'),
  ('tasitlar_otomobil-bmw-3-serisi-318i', 'Otomobil › BMW › 3 Serisi › 318i'),
  ('tasitlar_otomobil-bmw-3-serisi-318is', 'Otomobil › BMW › 3 Serisi › 318is'),
  ('tasitlar_otomobil-bmw-3-serisi-318tds', 'Otomobil › BMW › 3 Serisi › 318tds'),
  ('tasitlar_otomobil-bmw-3-serisi-318ti', 'Otomobil › BMW › 3 Serisi › 318ti'),
  ('tasitlar_otomobil-bmw-3-serisi-320cd', 'Otomobil › BMW › 3 Serisi › 320Cd'),
  ('tasitlar_otomobil-bmw-3-serisi-320ci', 'Otomobil › BMW › 3 Serisi › 320Ci'),
  ('tasitlar_otomobil-bmw-3-serisi-320d', 'Otomobil › BMW › 3 Serisi › 320d'),
  ('tasitlar_otomobil-bmw-3-serisi-320d-gt', 'Otomobil › BMW › 3 Serisi › 320d GT'),
  ('tasitlar_otomobil-bmw-3-serisi-320d-xdrive', 'Otomobil › BMW › 3 Serisi › 320d xDrive'),
  ('tasitlar_otomobil-bmw-3-serisi-320d-xdrive-gt', 'Otomobil › BMW › 3 Serisi › 320d xDrive GT'),
  ('tasitlar_otomobil-bmw-3-serisi-320i', 'Otomobil › BMW › 3 Serisi › 320i'),
  ('tasitlar_otomobil-bmw-3-serisi-320i-ed', 'Otomobil › BMW › 3 Serisi › 320i ED'),
  ('tasitlar_otomobil-bmw-3-serisi-320si', 'Otomobil › BMW › 3 Serisi › 320si'),
  ('tasitlar_otomobil-bmw-3-serisi-320td', 'Otomobil › BMW › 3 Serisi › 320td'),
  ('tasitlar_otomobil-bmw-3-serisi-323ci', 'Otomobil › BMW › 3 Serisi › 323Ci'),
  ('tasitlar_otomobil-bmw-3-serisi-323i', 'Otomobil › BMW › 3 Serisi › 323i'),
  ('tasitlar_otomobil-bmw-3-serisi-325ci', 'Otomobil › BMW › 3 Serisi › 325Ci'),
  ('tasitlar_otomobil-bmw-3-serisi-325d', 'Otomobil › BMW › 3 Serisi › 325d'),
  ('tasitlar_otomobil-bmw-3-serisi-325i', 'Otomobil › BMW › 3 Serisi › 325i'),
  ('tasitlar_otomobil-bmw-3-serisi-325i-xdrive', 'Otomobil › BMW › 3 Serisi › 325i xDrive'),
  ('tasitlar_otomobil-bmw-3-serisi-325tds', 'Otomobil › BMW › 3 Serisi › 325tds'),
  ('tasitlar_otomobil-bmw-3-serisi-325ti', 'Otomobil › BMW › 3 Serisi › 325ti'),
  ('tasitlar_otomobil-bmw-3-serisi-325xi', 'Otomobil › BMW › 3 Serisi › 325xi'),
  ('tasitlar_otomobil-bmw-3-serisi-328ci', 'Otomobil › BMW › 3 Serisi › 328Ci'),
  ('tasitlar_otomobil-bmw-3-serisi-328i', 'Otomobil › BMW › 3 Serisi › 328i'),
  ('tasitlar_otomobil-bmw-3-serisi-328i-xdrive', 'Otomobil › BMW › 3 Serisi › 328i xDrive'),
  ('tasitlar_otomobil-bmw-3-serisi-330cd', 'Otomobil › BMW › 3 Serisi › 330Cd'),
  ('tasitlar_otomobil-bmw-3-serisi-330ci', 'Otomobil › BMW › 3 Serisi › 330Ci'),
  ('tasitlar_otomobil-bmw-3-serisi-330d', 'Otomobil › BMW › 3 Serisi › 330d'),
  ('tasitlar_otomobil-bmw-3-serisi-330i', 'Otomobil › BMW › 3 Serisi › 330i'),
  ('tasitlar_otomobil-bmw-3-serisi-330i-xdrive', 'Otomobil › BMW › 3 Serisi › 330i xDrive'),
  ('tasitlar_otomobil-bmw-3-serisi-330xd', 'Otomobil › BMW › 3 Serisi › 330xd'),
  ('tasitlar_otomobil-bmw-3-serisi-330xi', 'Otomobil › BMW › 3 Serisi › 330xi'),
  ('tasitlar_otomobil-bmw-3-serisi-335d', 'Otomobil › BMW › 3 Serisi › 335d'),
  ('tasitlar_otomobil-bmw-3-serisi-335i', 'Otomobil › BMW › 3 Serisi › 335i'),
  ('tasitlar_otomobil-bmw-3-serisi-340d-xdrive', 'Otomobil › BMW › 3 Serisi › 340d xDrive'),
  ('tasitlar_otomobil-bmw-3-serisi-340i-xdrive', 'Otomobil › BMW › 3 Serisi › 340i xDrive')
on conflict (slug) do nothing;
