-- BMW 5 Serisi altı modeller (lib/categories.ts OTOMOBIL_MARKA_MODELS.bmw ile uyumlu).
insert into categories (slug, name)
values
  ('tasitlar_otomobil-bmw-5-serisi-518i', 'Otomobil › BMW › 5 Serisi › 518i'),
  ('tasitlar_otomobil-bmw-5-serisi-520', 'Otomobil › BMW › 5 Serisi › 520'),
  ('tasitlar_otomobil-bmw-5-serisi-520d', 'Otomobil › BMW › 5 Serisi › 520d'),
  ('tasitlar_otomobil-bmw-5-serisi-520d-gran-turismo', 'Otomobil › BMW › 5 Serisi › 520d Gran Turismo'),
  ('tasitlar_otomobil-bmw-5-serisi-520d-xdrive', 'Otomobil › BMW › 5 Serisi › 520d xDrive'),
  ('tasitlar_otomobil-bmw-5-serisi-520i', 'Otomobil › BMW › 5 Serisi › 520i'),
  ('tasitlar_otomobil-bmw-5-serisi-520li', 'Otomobil › BMW › 5 Serisi › 520Li'),
  ('tasitlar_otomobil-bmw-5-serisi-523i', 'Otomobil › BMW › 5 Serisi › 523i'),
  ('tasitlar_otomobil-bmw-5-serisi-524d', 'Otomobil › BMW › 5 Serisi › 524d'),
  ('tasitlar_otomobil-bmw-5-serisi-524td', 'Otomobil › BMW › 5 Serisi › 524td'),
  ('tasitlar_otomobil-bmw-5-serisi-525d', 'Otomobil › BMW › 5 Serisi › 525d'),
  ('tasitlar_otomobil-bmw-5-serisi-525d-xdrive', 'Otomobil › BMW › 5 Serisi › 525d xDrive'),
  ('tasitlar_otomobil-bmw-5-serisi-525i', 'Otomobil › BMW › 5 Serisi › 525i'),
  ('tasitlar_otomobil-bmw-5-serisi-525ix', 'Otomobil › BMW › 5 Serisi › 525ix'),
  ('tasitlar_otomobil-bmw-5-serisi-525td', 'Otomobil › BMW › 5 Serisi › 525td'),
  ('tasitlar_otomobil-bmw-5-serisi-525tds', 'Otomobil › BMW › 5 Serisi › 525tds'),
  ('tasitlar_otomobil-bmw-5-serisi-525-xdrive', 'Otomobil › BMW › 5 Serisi › 525 xDrive'),
  ('tasitlar_otomobil-bmw-5-serisi-528i', 'Otomobil › BMW › 5 Serisi › 528i'),
  ('tasitlar_otomobil-bmw-5-serisi-528i-xdrive', 'Otomobil › BMW › 5 Serisi › 528i xDrive'),
  ('tasitlar_otomobil-bmw-5-serisi-530d', 'Otomobil › BMW › 5 Serisi › 530d'),
  ('tasitlar_otomobil-bmw-5-serisi-530d-xdrive', 'Otomobil › BMW › 5 Serisi › 530d xDrive'),
  ('tasitlar_otomobil-bmw-5-serisi-530i', 'Otomobil › BMW › 5 Serisi › 530i'),
  ('tasitlar_otomobil-bmw-5-serisi-530i-xdrive', 'Otomobil › BMW › 5 Serisi › 530i xDrive'),
  ('tasitlar_otomobil-bmw-5-serisi-530xd-gran-turismo', 'Otomobil › BMW › 5 Serisi › 530xd Gran Turismo'),
  ('tasitlar_otomobil-bmw-5-serisi-530-xdrive', 'Otomobil › BMW › 5 Serisi › 530 xDrive'),
  ('tasitlar_otomobil-bmw-5-serisi-530xi', 'Otomobil › BMW › 5 Serisi › 530xi'),
  ('tasitlar_otomobil-bmw-5-serisi-535d', 'Otomobil › BMW › 5 Serisi › 535d'),
  ('tasitlar_otomobil-bmw-5-serisi-535d-xdrive', 'Otomobil › BMW › 5 Serisi › 535d xDrive'),
  ('tasitlar_otomobil-bmw-5-serisi-535i', 'Otomobil › BMW › 5 Serisi › 535i'),
  ('tasitlar_otomobil-bmw-5-serisi-535i-xdrive', 'Otomobil › BMW › 5 Serisi › 535i xDrive'),
  ('tasitlar_otomobil-bmw-5-serisi-540i', 'Otomobil › BMW › 5 Serisi › 540i'),
  ('tasitlar_otomobil-bmw-5-serisi-540i-xdrive', 'Otomobil › BMW › 5 Serisi › 540i xDrive'),
  ('tasitlar_otomobil-bmw-5-serisi-545i', 'Otomobil › BMW › 5 Serisi › 545i'),
  ('tasitlar_otomobil-bmw-5-serisi-550d-xdrive', 'Otomobil › BMW › 5 Serisi › 550d xDrive'),
  ('tasitlar_otomobil-bmw-5-serisi-550-xdrive', 'Otomobil › BMW › 5 Serisi › 550 xDrive')
on conflict (slug) do nothing;
