-- Citroën, Fiat, Ford, Hyundai, Opel modelleri (lib/categories.ts OTOMOBIL_MARKA_MODELS).
insert into categories (slug, name)
values
  ('tasitlar_otomobil-citroen-ami', 'Otomobil › Citroën › AMI'),
  ('tasitlar_otomobil-citroen-c-elysee', 'Otomobil › Citroën › C-Elysée'),
  ('tasitlar_otomobil-citroen-c1', 'Otomobil › Citroën › C1'),
  ('tasitlar_otomobil-citroen-c2', 'Otomobil › Citroën › C2'),
  ('tasitlar_otomobil-citroen-c3', 'Otomobil › Citroën › C3'),
  ('tasitlar_otomobil-citroen-e-c3', 'Otomobil › Citroën › e-C3'),
  ('tasitlar_otomobil-citroen-c3-picasso', 'Otomobil › Citroën › C3 Picasso'),
  ('tasitlar_otomobil-citroen-c4', 'Otomobil › Citroën › C4'),
  ('tasitlar_otomobil-citroen-c4-grand-picasso', 'Otomobil › Citroën › C4 Grand Picasso'),
  ('tasitlar_otomobil-citroen-c4-picasso', 'Otomobil › Citroën › C4 Picasso'),
  ('tasitlar_otomobil-citroen-c4-x', 'Otomobil › Citroën › C4 X'),
  ('tasitlar_otomobil-citroen-e-c4', 'Otomobil › Citroën › e-C4'),
  ('tasitlar_otomobil-citroen-e-c4-x', 'Otomobil › Citroën › e-C4 X'),
  ('tasitlar_otomobil-citroen-c5', 'Otomobil › Citroën › C5'),
  ('tasitlar_otomobil-citroen-c6', 'Otomobil › Citroën › C6'),
  ('tasitlar_otomobil-citroen-c8', 'Otomobil › Citroën › C8'),
  ('tasitlar_otomobil-citroen-saxo', 'Otomobil › Citroën › Saxo'),
  ('tasitlar_otomobil-citroen-xsara', 'Otomobil › Citroën › Xsara'),
  ('tasitlar_otomobil-citroen-bx', 'Otomobil › Citroën › BX'),
  ('tasitlar_otomobil-citroen-xantia', 'Otomobil › Citroën › Xantia'),
  ('tasitlar_otomobil-citroen-xm', 'Otomobil › Citroën › XM'),
  ('tasitlar_otomobil-citroen-zx', 'Otomobil › Citroën › ZX'),
  ('tasitlar_otomobil-fiat-124-spider', 'Otomobil › Fiat › 124 Spider'),
  ('tasitlar_otomobil-fiat-albea', 'Otomobil › Fiat › Albea'),
  ('tasitlar_otomobil-fiat-brava', 'Otomobil › Fiat › Brava'),
  ('tasitlar_otomobil-fiat-bravo', 'Otomobil › Fiat › Bravo'),
  ('tasitlar_otomobil-fiat-126-bis', 'Otomobil › Fiat › 126 Bis'),
  ('tasitlar_otomobil-fiat-coupe', 'Otomobil › Fiat › Coupe'),
  ('tasitlar_otomobil-fiat-croma', 'Otomobil › Fiat › Croma'),
  ('tasitlar_otomobil-fiat-500-ailesi', 'Otomobil › Fiat › 500 Ailesi'),
  ('tasitlar_otomobil-fiat-egea', 'Otomobil › Fiat › Egea'),
  ('tasitlar_otomobil-fiat-idea', 'Otomobil › Fiat › Idea'),
  ('tasitlar_otomobil-fiat-linea', 'Otomobil › Fiat › Linea'),
  ('tasitlar_otomobil-fiat-marea', 'Otomobil › Fiat › Marea'),
  ('tasitlar_otomobil-fiat-mirafiori', 'Otomobil › Fiat › Mirafiori'),
  ('tasitlar_otomobil-fiat-palio', 'Otomobil › Fiat › Palio'),
  ('tasitlar_otomobil-fiat-panda', 'Otomobil › Fiat › Panda'),
  ('tasitlar_otomobil-fiat-punto', 'Otomobil › Fiat › Punto'),
  ('tasitlar_otomobil-fiat-siena', 'Otomobil › Fiat › Siena'),
  ('tasitlar_otomobil-fiat-stilo', 'Otomobil › Fiat › Stilo'),
  ('tasitlar_otomobil-fiat-tempra', 'Otomobil › Fiat › Tempra'),
  ('tasitlar_otomobil-fiat-tipo', 'Otomobil › Fiat › Tipo'),
  ('tasitlar_otomobil-fiat-topolino', 'Otomobil › Fiat › Topolino'),
  ('tasitlar_otomobil-fiat-ulysse', 'Otomobil › Fiat › Ulysse'),
  ('tasitlar_otomobil-fiat-uno', 'Otomobil › Fiat › UNO'),
  ('tasitlar_otomobil-ford-b-max', 'Otomobil › Ford › B-Max'),
  ('tasitlar_otomobil-ford-c-max', 'Otomobil › Ford › C-Max'),
  ('tasitlar_otomobil-ford-escort', 'Otomobil › Ford › Escort'),
  ('tasitlar_otomobil-ford-fiesta', 'Otomobil › Ford › Fiesta'),
  ('tasitlar_otomobil-ford-focus', 'Otomobil › Ford › Focus'),
  ('tasitlar_otomobil-ford-fusion', 'Otomobil › Ford › Fusion'),
  ('tasitlar_otomobil-ford-galaxy', 'Otomobil › Ford › Galaxy'),
  ('tasitlar_otomobil-ford-grand-c-max', 'Otomobil › Ford › Grand C-Max'),
  ('tasitlar_otomobil-ford-ka', 'Otomobil › Ford › Ka'),
  ('tasitlar_otomobil-ford-mondeo', 'Otomobil › Ford › Mondeo'),
  ('tasitlar_otomobil-ford-mustang', 'Otomobil › Ford › Mustang'),
  ('tasitlar_otomobil-ford-s-max', 'Otomobil › Ford › S-Max'),
  ('tasitlar_otomobil-ford-taurus', 'Otomobil › Ford › Taurus'),
  ('tasitlar_otomobil-ford-cougar', 'Otomobil › Ford › Cougar'),
  ('tasitlar_otomobil-ford-festiva', 'Otomobil › Ford › Festiva'),
  ('tasitlar_otomobil-ford-granada', 'Otomobil › Ford › Granada'),
  ('tasitlar_otomobil-ford-orion', 'Otomobil › Ford › Orion'),
  ('tasitlar_otomobil-ford-probe', 'Otomobil › Ford › Probe'),
  ('tasitlar_otomobil-ford-scorpio', 'Otomobil › Ford › Scorpio'),
  ('tasitlar_otomobil-ford-sierra', 'Otomobil › Ford › Sierra'),
  ('tasitlar_otomobil-ford-taunus', 'Otomobil › Ford › Taunus'),
  ('tasitlar_otomobil-ford-thunderbird', 'Otomobil › Ford › Thunderbird'),
  ('tasitlar_otomobil-hyundai-accent', 'Otomobil › Hyundai › Accent'),
  ('tasitlar_otomobil-hyundai-accent-blue', 'Otomobil › Hyundai › Accent Blue'),
  ('tasitlar_otomobil-hyundai-accent-era', 'Otomobil › Hyundai › Accent Era'),
  ('tasitlar_otomobil-hyundai-atos', 'Otomobil › Hyundai › Atos'),
  ('tasitlar_otomobil-hyundai-centennial', 'Otomobil › Hyundai › Centennial'),
  ('tasitlar_otomobil-hyundai-coupe', 'Otomobil › Hyundai › Coupe'),
  ('tasitlar_otomobil-hyundai-elantra', 'Otomobil › Hyundai › Elantra'),
  ('tasitlar_otomobil-hyundai-excel', 'Otomobil › Hyundai › Excel'),
  ('tasitlar_otomobil-hyundai-genesis', 'Otomobil › Hyundai › Genesis'),
  ('tasitlar_otomobil-hyundai-getz', 'Otomobil › Hyundai › Getz'),
  ('tasitlar_otomobil-hyundai-grandeur', 'Otomobil › Hyundai › Grandeur'),
  ('tasitlar_otomobil-hyundai-i10', 'Otomobil › Hyundai › i10'),
  ('tasitlar_otomobil-hyundai-i20', 'Otomobil › Hyundai › i20'),
  ('tasitlar_otomobil-hyundai-i20-active', 'Otomobil › Hyundai › i20 Active'),
  ('tasitlar_otomobil-hyundai-i20-n', 'Otomobil › Hyundai › i20 N'),
  ('tasitlar_otomobil-hyundai-i30', 'Otomobil › Hyundai › i30'),
  ('tasitlar_otomobil-hyundai-i40', 'Otomobil › Hyundai › i40'),
  ('tasitlar_otomobil-hyundai-ioniq', 'Otomobil › Hyundai › Ioniq'),
  ('tasitlar_otomobil-hyundai-ioniq-6', 'Otomobil › Hyundai › Ioniq 6'),
  ('tasitlar_otomobil-hyundai-ix20', 'Otomobil › Hyundai › iX20'),
  ('tasitlar_otomobil-hyundai-matrix', 'Otomobil › Hyundai › Matrix'),
  ('tasitlar_otomobil-hyundai-s-coupe', 'Otomobil › Hyundai › S-Coupe'),
  ('tasitlar_otomobil-hyundai-sonata', 'Otomobil › Hyundai › Sonata'),
  ('tasitlar_otomobil-hyundai-trajet', 'Otomobil › Hyundai › Trajet'),
  ('tasitlar_otomobil-opel-adam', 'Otomobil › Opel › Adam'),
  ('tasitlar_otomobil-opel-agila', 'Otomobil › Opel › Agila'),
  ('tasitlar_otomobil-opel-ascona', 'Otomobil › Opel › Ascona'),
  ('tasitlar_otomobil-opel-astra', 'Otomobil › Opel › Astra'),
  ('tasitlar_otomobil-opel-astra-e', 'Otomobil › Opel › Astra-e'),
  ('tasitlar_otomobil-opel-calibra', 'Otomobil › Opel › Calibra'),
  ('tasitlar_otomobil-opel-cascada', 'Otomobil › Opel › Cascada'),
  ('tasitlar_otomobil-opel-corsa', 'Otomobil › Opel › Corsa'),
  ('tasitlar_otomobil-opel-corsa-e', 'Otomobil › Opel › Corsa-e'),
  ('tasitlar_otomobil-opel-gt-roadster', 'Otomobil › Opel › GT (Roadster)'),
  ('tasitlar_otomobil-opel-insignia', 'Otomobil › Opel › Insignia'),
  ('tasitlar_otomobil-opel-kadett', 'Otomobil › Opel › Kadett'),
  ('tasitlar_otomobil-opel-manta', 'Otomobil › Opel › Manta'),
  ('tasitlar_otomobil-opel-meriva', 'Otomobil › Opel › Meriva'),
  ('tasitlar_otomobil-opel-omega', 'Otomobil › Opel › Omega'),
  ('tasitlar_otomobil-opel-rekord', 'Otomobil › Opel › Rekord'),
  ('tasitlar_otomobil-opel-signum', 'Otomobil › Opel › Signum'),
  ('tasitlar_otomobil-opel-tigra', 'Otomobil › Opel › Tigra'),
  ('tasitlar_otomobil-opel-vectra', 'Otomobil › Opel › Vectra'),
  ('tasitlar_otomobil-opel-zafira', 'Otomobil › Opel › Zafira')
on conflict (slug) do nothing;
