-- Kategoriler bos/supabase ilk kurulum: SQL Editor'da bir kez calistir.
-- lib/categories.ts ile uyumlu slug + gorunen ad (Satariz-benzeri etiketler).

insert into categories (slug, name)
values
  ('tasitlar_otomobil', 'Araç'),
  ('tasitlar_motosiklet', 'Motosiklet'),
  ('tasitlar_bisiklet', 'Bisiklet'),
  ('tasitlar_ticari-araclar', 'Ticari araç'),
  ('tasitlar_deniz-tasitlari', 'Deniz aracı (tekne, yat)'),
  ('gayrimenkul_konut', 'Konut'),
  ('gayrimenkul_ev', 'Müstakil ev'),
  ('gayrimenkul_arsa', 'Arsa'),
  ('gayrimenkul_daire', 'Daire'),
  ('gayrimenkul_villa', 'Villa'),
  ('gayrimenkul_isyeri-ofis', 'İş yeri'),
  ('gayrimenkul_toprak', 'Toprak & tarla'),
  ('gayrimenkul_depo-garaj', 'Depo & garaj'),
  ('elektronik_telefon', 'Cep telefonu'),
  ('elektronik_bilgisayar-tablet', 'Bilgisayar & tablet'),
  ('elektronik_televizyon', 'TV & görüntü'),
  ('elektronik_beyaz-esya', 'Beyaz eşya'),
  ('elektronik_ses-hoparlor', 'Ses & görüntü'),
  ('moda-kisisel_giyim', 'Giyim'),
  ('moda-kisisel_ayakkabi', 'Ayakkabı'),
  ('moda-kisisel_canta-aksesuar', 'Çanta & Aksesuar'),
  ('moda-kisisel_saat-taki', 'Saat & Takı'),
  ('ev-yasam_mobilya', 'Mobilya'),
  ('ev-yasam_ev-dekorasyonu', 'Ev dekorasyon'),
  ('ev-yasam_mutfak-esyalari', 'Mutfak'),
  ('ev-yasam_bahce-balkon', 'Bahçe & balkon'),
  ('hobi-eglence_oyun-konsolu-oyunlar', 'Oyun & konsol'),
  ('hobi-eglence_spor-malzemeleri', 'Spor'),
  ('hobi-eglence_muzik-aletleri', 'Müzik'),
  ('hobi-eglence_koleksiyon-urunleri', 'Koleksiyon'),
  ('hayvanlar_evcil-hayvanlar', 'Evcil hayvan'),
  ('hayvanlar_hayvan-aksesuarlari', 'Aksesuar'),
  ('hayvanlar_mama-bakim-urunleri', 'Mama & bakım'),
  ('is-sanayi_tarim-makineleri', 'Tarım makinesi'),
  ('is-sanayi_insaat-ekipmanlari', 'İnşaat'),
  ('is-sanayi_el-aletleri', 'El aleti'),
  ('is-sanayi_ofis-malzemeleri', 'Ofis')
on conflict (slug) do nothing;
